### ISSUE TITLE
DiscordEmbed Webhooks arbitrarily posting doubles 

### ISSUE THREAD

**Issue by morriscotty** [lovvskillz/python-discord-webhook#1]
I'm posting the same embedded content to multiple (5 in total) different discord channels. Each DiscordWebhook is executed within the same function where the one DiscordEmbed is declared i.e.

```
webhook1.add_embed(embed)
webhook1.execute()

webhook2.add_embed(embed)
webhook2.execute()
...
```

were each webhook[x] is a separate DiscordWebhook and embed is a single reused DiscordEmbed.

The issue is that sometimes the embedded post appears multiple times in each specified channel. For now I'm having to remove the duplicates manually. 

Any ideas on what could be causing the issue? I've had a look but nothing is sticking out at me.

**Comment by morriscotty** [comment]
It is only happening sometimes for myself so may be hard to reproduce and does make me think it could be some sort of latency issue either on Discord's end or Heroku's end where the script is hosted. The function is definitely only being called once, I also have a slack and twitter script that is called at the same time without these issues.

Below is the script being used with some data retracted and dummy data in its place:

```
...
from discord_webhook.webhook import DiscordWebhook, DiscordEmbed
...

#Defined globally
webhook1 = DiscordWebhook(url='webhook_url',username="Usernmame")
webhook2 = DiscordWebhook(url='webhook_url',username="Usernmame")
webhook3 = DiscordWebhook(url='webhook_url',username="Usernmame")
webhook4 = DiscordWebhook(url='webhook_url',username="Usernmame")
webhook5 = DiscordWebhook(url='webhook_url',username="Usernmame")

...

def post_discord():
    embed = DiscordEmbed(title='Title', description='Description')
    embed.set_footer(text='My Footer')
    embed.set_timestamp()
	embed.add_embed_field(name='My Field', value='Field Value')
    embed.set_thumbnail(url='thumbnail_url')

    webhook1.add_embed(embed)
    webhook1.execute()

    webhook2.add_embed(embed)
    webhook2.execute()

    webhook3.add_embed(embed)
    webhook3.execute()

    webhook4.add_embed(embed)
    webhook4.execute()

    webhook5.add_embed(embed)
    webhook5.execute()

	
...

def live():
    if request.method == 'POST':
        ...
        post_discord()
        ...
    else:
        ...
```

**Comment by lovvskillz** [comment]
I tried it but I don't get the same message multiple times.
If I execute the function in a loop, I received the same embed message multiple times.
But this behavior was expected because another `embed` was added to the webhook.

```python
from discord_webhook.webhook import DiscordWebhook, DiscordEmbed

embed = DiscordEmbed(title='Title', color=242424)
webhook1 = DiscordWebhook(url="URL")
webhook2 = DiscordWebhook(url="URL")
webhook3 = DiscordWebhook(url="URL")
webhook4 = DiscordWebhook(url="URL")
webhook5 = DiscordWebhook(url="URL")


def post():
    webhook1.add_embed(embed)
    webhook1.execute()
    webhook2.add_embed(embed)
    webhook2.execute()
    webhook3.add_embed(embed)
    webhook3.execute()
    webhook4.add_embed(embed)
    webhook4.execute()
    webhook5.add_embed(embed)
    webhook5.execute()


i = 0
while i < 3:
    embed.set_description(i)
    i += 1
    post()
```
![grafik](https://user-images.githubusercontent.com/14542790/46416834-abd0b080-c728-11e8-96da-94c71f42deab.png)

You could remove the embed from the webhook after it was executed. Maybe this will fix it.
```python
from discord_webhook.webhook import DiscordWebhook, DiscordEmbed

embed = DiscordEmbed(title='Title', color=242424)
webhook1 = DiscordWebhook(url="URL")
webhook2 = DiscordWebhook(url="URL")
webhook3 = DiscordWebhook(url="URL")
webhook4 = DiscordWebhook(url="URL")
webhook5 = DiscordWebhook(url="URL")


def post():
    webhook1.add_embed(embed)
    webhook1.execute()
    webhook1.remove_embed(0) # remove from index 0

    webhook2.add_embed(embed)
    webhook2.execute()
    webhook2.remove_embed(0)

    webhook3.add_embed(embed)
    webhook3.execute()
    webhook3.remove_embed(0)

    webhook4.add_embed(embed)
    webhook4.execute()
    webhook4.remove_embed(0)

    webhook5.add_embed(embed)
    webhook5.execute()
    webhook5.remove_embed(0)


i = 0
while i < 3:
    embed.set_description(i)
    i += 1
    post()
```

![grafik](https://user-images.githubusercontent.com/14542790/46417456-01f22380-c72a-11e8-8d13-a1eeabaa87f3.png)

**Comment by vremes** [comment]
I also encountered this issue, but i wrote subclass that overrides `execute` method and makes sure there are no embeds left over in `self.embeds` after `execute` is called.

Example:
```python
from discord_webhook import DiscordWebhook

class CustomDiscordWebhook(DiscordWebhook):
    def execute(self):
        e = super().execute()

        embeds = self.get_embeds()
        for i, embed in enumerate(embeds):
            self.remove_embed(i)

        return e

discord_webhook = CustomDiscordWebHook(url=[...])
```

I've taken a closer look at the code in this repository and calling `DiscordWebhook.execute` methods calls `DiscordWebhook.json` which should set `self.embeds` to empty list, but i guess there is some kind of condition where this fails.
