### ISSUE TITLE
Rate Limit information

### ISSUE THREAD

**Issue by BurningNacho** [lovvskillz/python-discord-webhook#10]
Ive been trying to get the information that disctord webhooks should return when rate limits are applied as seen in [discord developer portal](https://discordapp.com/developers/docs/topics/rate-limits) and I can't find a way to get the data using this module. Is there a way to get this data? If there is no way, are you pretending on updating this?

Edit:
It may be as easy as returning the response when calling webhook.execute()
https://github.com/lovvskillz/python-discord-webhook/blob/5278184078c9da9362b6343c478a92e0904a7f83/discord_webhook/webhook.py#L102

**Comment by lovvskillz** [comment]
Okay, I'll take a look.

**Comment by BurningNacho** [comment]
I've tryied to use the logger and I don't seem to get any error log but after the 10th webhook i execute within a minute my messages are discarted

**Comment by lovvskillz** [comment]
I updated the package.  
`.execute()` now returns the response 
```
response = webhook.execute()
print(response.headers.get('x-ratelimit-limit'))
print(response.headers.get('x-ratelimit-remaining'))
```

**Comment by BurningNacho** [comment]
Thank you so much for that! :)
