### ISSUE TITLE
AttributeError: 'DiscordEmbed' object has no attribute 'add_field'

### ISSUE THREAD

**Issue by iestatic** [lovvskillz/python-discord-webhook#100]
AttributeError: 'DiscordEmbed' object has no attribute 'add_field'

This doesn't allow the add_field feature for the discord embeds.

**Comment by vremes** [comment]
Hey,

The method  name is `add_embed_field`, not `add_field`.

Example code:
```py
from discord_webhook import DiscordEmbed

embed = DiscordEmbed()
embed.add_embed_field(name='My field', value='Hello world')
```
