### ISSUE TITLE
Ability to delete messages sent from a webhook a few days later.

### ISSUE THREAD

**Issue by beuaaa** [lovvskillz/python-discord-webhook#107]
I want to delete all the messages I sent with DiscordWebhook but not in the same run as in your example:
```python
from discord_webhook import DiscordWebhook
from time import sleep

webhook = DiscordWebhook(url='your webhook url', content='Webhook Content')
sent_webhook = webhook.execute()
sleep(10)
webhook.delete(sent_webhook)
```

I would like something like:

```python
from discord_webhook import DiscordWebhook

webhook = DiscordWebhook(url='your webhook url', content='Webhook Content')
sent_webhook = webhook.execute()
sent_webhook .save('sent_webhook .swh')
```

And then a few days later, the following imaginary code is executed:

```python
from discord_webhook import DiscordWebhook

webhook, sent_webhook = DiscordWebhook(file='sent_webhook.swh')
webhook.delete(sent_webhook)
```

Is it possible?

**Comment by kshubham506** [comment]
Yes, you can simply modify the code to accept message ids. Like this : https://github.com/kshubham506/python-discord-webhook/blob/master/discord_webhook/async_webhook.py#L190
Note : you will have to store the sent message ids somewhere , in order to use them later either in edit/delete etc.

**Comment by beuaaa** [comment]
Thanks a lot @kshubham506 . I think you did the work with your fork so I will use your fork while this new feature is added in the original repo. With your fork how do you get the  id of the sent message?

@lovvskillz I hope this change will be merged into this repo. Do you think there is a chance to merge this new feature? If yes, when?

**Comment by kshubham506** [comment]
> Thanks a lot @kshubham506 . I think you did the work with your fork so I will use your fork while this new feature is added in the original repo. With your fork how do you get the id of the sent message?
> 
> @lovvskillz I hope this change will be merged into this repo. Do you think there is a chance to merge this new feature? If yes, when?

HI @beuaaa , I use redis to store the sent message ids, ( i don't need the ids' indefinitely so redis pretty much solves all my use cases)

**Comment by lovvskillz** [comment]
@beuaaa I'm currently rewriting the code to allow for something like this.
In the end, this is how it will be possible:
```python
webhook = DiscordWebhook(url="url")
webhook.execute()
print(webhook.id)

# ... after some period of time

webhook = DiscordWebhook(url="url", id="webhook id")
response = webhook.delete()
```
So you'll need to save the returned webhook id which will be available in the new `webhook.id` property.

**Comment by lovvskillz** [comment]
@beuaaa Should be possible with the new released version. Please keep the breaking changes in mind.

**Comment by beuaaa** [comment]
Thanks a lot @lovvskillz, when do you think the new released version will be availabe on pypi.org?

**Comment by lovvskillz** [comment]
It's already available.

**Comment by beuaaa** [comment]
I've tried to update my package with pip but it's still [the version 0.17.0](https://pypi.org/project/discord-webhook/).

**Comment by beuaaa** [comment]
I just tried it and it works perfectly. Keep up the good work!
