### ISSUE TITLE
Take into account the commands of the bots

### ISSUE THREAD

**Issue by beuaaa** [lovvskillz/python-discord-webhook#108]
I have Mee6 in a channel and I would like to send it a command like "!clear 100".

If I send my command like this
```python
webhook = DiscordWebhook(url='your webhook url', content='!clear 100')
response = webhook.execute()
```
It is not executed by Mee6

How to make the bot execute the command?

**Comment by Tithen-Firion** [comment]
You set the **bot** to accept bot messages. By default most bots accept user messages only.
