### ISSUE TITLE
Particular image not showing when embedded with BeautifulSoup

### ISSUE THREAD

**Issue by Spykerwolf** [lovvskillz/python-discord-webhook#109]
Hey all. I don't understand why this particular image is not being displayed on Discord as an embedded post. Other sites work fine, but this particular jpg is not showing. I've tried using the url instead of the variable, but getting the same result. See below - that's what I can see. I've also simplified the code below for readability sakes.

```
from bs4 import BeautifulSoup
import requests
from discord_webhook import DiscordWebhook, DiscordEmbed

url = "https://koanga.org.nz/gardens/perennials/kumara/kumara-reka-rawa/"
r = requests.get(url)
soup = BeautifulSoup(r.text, "html.parser")

image = soup.select("img.attachment-shop-single")[0]['src']
# This shows https://koanga.org.nz/wp-content/uploads/2022/07/kumara_reka_rawa.jpg with print

webhook = DiscordWebhook(url="myWebhookURL")
embed = DiscordEmbed(description="Test", color='03b2f8')
embed.set_author(name='Koanga', url=url, icon_url=logo)
embed.add_embed_field(name='Price', value="Test")

# This is the particular line that's not working. If I use a different image from a different site, then it works. So the discord integration works, but not sure why this image is not showing.
embed.set_image(url=image)

webhook.add_embed(embed)
response = webhook.execute()
```

![image](https://user-images.githubusercontent.com/26391619/201567360-1b29a188-9a52-44d4-894f-cbb82741f778.png)

**Comment by Tithen-Firion** [comment]
Because that website blocks Discord. Try pasting that link yourself on Discord - the image won't show up. You can fix it by downloading the image yourself and attaching it as a file:
```py
r2 = requests.get(image)
webhook.add_file(r2.content, "image.jpg")
embed.set_image(url="attachment://image.jpg")
```

**Comment by Tithen-Firion** [comment]
I just tested it. Ran your code, replaced image URL with something else (worked fine), then hardcoded the image you wanted (didn't work), then confirmed by sending the link to image on Discord.
