### ISSUE TITLE
Multiple webhooks support?

### ISSUE THREAD

**Issue by arnold427** [lovvskillz/python-discord-webhook#11]
Hey! Are you planning to add multiple webhooks support?

**Comment by RHQ-Rusty** [comment]
> Hey! Are you planning to add multiple webhooks support?

@arnold427 Multiple webhooks can be used. Depending on the context of what you're doing, it could look something like this.

```
url1 = <url here>
url2 = <url here>
wh1 = DiscordWebhook(url=url1, content=contentvariable)
wh2 = DiscordWebhook(url=url2, content=2ndwhcontentvariable)
```

**Comment by arnold427** [comment]
If you can do something like:
wh1 = DiscordWebhook(url=url1,url2,url3 content=contentvariable)

I think it would be much easier since you don't have to add embed and execute one by one.

**Comment by RHQ-Rusty** [comment]
Ah, that is my bad, I thought you meant multiple different messages to multiple different webhooks. To send the same content to multiple URLs, that's something entirely different. I agree!

**Comment by lovvskillz** [comment]
you can do this with the latest release (0.6.0)

```python
webhook_urls = ['webhook url 1', 'webhook url 2']
webhook = DiscordWebhook(url=webhook_urls, content='Webhook Message')
response = webhook.execute()
```

**Comment by idealsignals** [comment]
You can no longer do this in v1.0.0?

**Comment by lovvskillz** [comment]
@idealsignals 
This is the new way:
```
webhook1, webhook2 = DiscordWebhook.create_batch(urls=['first url', 'second url'], content='Webhook Message')
response1 = webhook1.execute()
response2 = webhook2.execute()
```

**Comment by lovvskillz** [comment]
You could use a for loop.
