### ISSUE TITLE
Multiple webhook URLs not working in v1.0.0

### ISSUE THREAD

**Issue by vhoch** [lovvskillz/python-discord-webhook#122]
Hello, when trying to use multiple webhook URLs the code throws this:

raise InvalidSchema(f"No connection adapters were found for {url!r}")
requests.exceptions.InvalidSchema: No connection adapters were found for "['https://discord.com/api/webhooks/...']"

Code:
`from discord_webhook import DiscordWebhook

webhook_urls = ['webhook url 1', 'webhook url 2']
webhook = DiscordWebhook(url=webhook_urls, content='Webhook Message')
response = webhook.execute()`

It worked with v0.17.0
I assume it's because the double quotes (as shown in the error)

Or is there a new way of sending multiple webhooks that I missed?

**Comment by vhoch** [comment]
On the website, it shows sending to multiple URLs is working the same way as before but in the Github README it's not mentioned, so I assume I have to create multiple instances (if it's still possible to send to multiple URLs in one go please let me know)

**Comment by lovvskillz** [comment]
Unfortunately, the readme on PyPI is no longer up to date. Use the new `create_batch` function if you need to work with multiple URLs.
