### ISSUE TITLE
Can't remove files when using webhook.edit()

### ISSUE THREAD

**Issue by RandomModderJDK** [lovvskillz/python-discord-webhook#123]
I want to reopen [#73](https://github.com/lovvskillz/python-discord-webhook/issues/73).
The solution isn't working anymore, because you cant give any parameters to webhook.edit()

**Comment by lovvskillz** [comment]
I have already started working on a fix, but I have noticed another problem. I think I can continue working on it today.

**Comment by lovvskillz** [comment]
Should be fixed in version 1.1.0

example:
```python
webhook.execute()
webhook.remove_files()
webhook.edit()
```
