### ISSUE TITLE
Timezone for set_timestamp()

### ISSUE THREAD

**Issue by OmarSaidIbrahim** [lovvskillz/python-discord-webhook#124]
Would be great to add support for the timezone while setting the set_timestamp on the embed

**Comment by lovvskillz** [comment]
Added with this commit, but it's not released yet: https://github.com/lovvskillz/python-discord-webhook/commit/c432af7e2ed4b626f7d09d87449dd1a08479d0a1

Just set the timestamp as a datetime object (with your timezone).
