### ISSUE TITLE
Add better support for sending several images

### ISSUE THREAD

**Issue by TheLovinator1** [lovvskillz/python-discord-webhook#126]
You can send up to 4 images in a embed if you add a URL to the embed:

![Discord_t4sLM7cqsN](https://user-images.githubusercontent.com/4153203/227569225-e758bc77-3562-43fd-aca2-f5ac278c5bc1.png)

```python
from discord_webhook import DiscordEmbed, DiscordWebhook

embed1 = DiscordEmbed(url="https://example.com") # Needs to have the same URL
embed2 = DiscordEmbed(url="https://example.com")
embed3 = DiscordEmbed(url="https://example.com")
embed4 = DiscordEmbed(url="https://example.com")

embed1.set_image(url="https://pbs.twimg.com/media/Fr_oHEkWIAUodqE?format=png&name=240x240")
embed2.set_image(url="https://pbs.twimg.com/media/Fr_oHFBXsAEu3Wk?format=png&name=240x240")
embed3.set_image(url="https://pbs.twimg.com/media/Fr_oHFfWYAINMbs?format=png&name=240x240")
embed4.set_image(url="https://pbs.twimg.com/media/Fr_oHGDXwAYAGu4?format=png&name=240x240")

hook = DiscordWebhook(
    url="",
    embeds=[embed1, embed2, embed3, embed4],
)

response = hook.execute()

```

Is it possible to just use one embed and pass a list of images to set_image? Am I doing this wrong?

**Comment by Niroc** [comment]
Try doing it like this and it'll work...
`from discord_webhook import DiscordWebhook, DiscordEmbed

webhook = DiscordWebhook(url='your webhook url')

# create embed object for webhook
embed = DiscordEmbed(title='Put title on first embed', description='and put the description  on first embed', color='03b2f8')

# set 1st image
embed.set_image(url='https://cdn.donmai.us/sample/0f/d3/sample-0fd3d43d3680925a4a1c60d2e5f09cd4.jpg')

# this can be junk but it, must be the same on every embed
embed.set_url('https://astrixbot.cf')

# add embed object to webhook
webhook.add_embed(embed)

# false embed for the second image
embed2 = DiscordEmbed()

# set 2nd image
embed2.set_image(url='https://cdn.donmai.us/sample/0c/ab/sample-0cab49d9c58fce71a44cdb0ebe12d0d8.jpg')

# this can be junk but it, must be the same on every embed
embed2.set_url('https://astrixbot.cf')

# add 2nd embed object to webhook
webhook.add_embed(embed2)

# send all your webhooks
response = webhook.execute()
`
when I run that I get this...
![image](https://user-images.githubusercontent.com/12100786/234686519-f25cddf2-2555-4c16-999d-c9fab03a2b6b.png)
