### ISSUE TITLE
Webhook status code 400

### ISSUE THREAD

**Issue by laszlolaszlo** [lovvskillz/python-discord-webhook#140]
Hello,

With release 1.1.0 I can send message to my channel, but with 1.2.0 I got this error:
`Webhook status code 400: {"tts": ["Must be either true or false."]}`

This is my very simple code which works fine with 1.1.0:
```
    for webhook_url in webhook_urls:
        webhook = DiscordWebhook(
            url=webhook_url.url, content=final_message, timeout=5.0
        )
        try:
            response = webhook.execute()
        except Timeout as err:
            print(f"Oops! Connection to Discord timed out: {err}")
```
Python 3.11.4

**Comment by laszlolaszlo** [comment]
In Discord documentation: https://discord.com/developers/docs/resources/webhook
**tts** is a **optional** boolean type field.
If you need any other information to debug this issue please let me know.

**Comment by lovvskillz** [comment]
Thanks for notifying me about the problem. In version 1.2.1 the problem is fixed.
