### ISSUE TITLE
Allowed mentions now expects a dictionary and not a list

### ISSUE THREAD

**Issue by cemathey** [lovvskillz/python-discord-webhook#146]
`Webhook status code 400: {"allowed_mentions": ["Expected an object/dictionary."]}`

The Discord API has apparently changed and now [allowed_mentions](https://github.com/lovvskillz/python-discord-webhook/blob/fc1596d71810c09ab5a84ba5fd0c94eee6276471/discord_webhook/webhook.py#L222) expects a dictionary.

For example this works successfully:

```python
{'users': ['296385262794178570'], 'roles': ['1190040849036361808']}
```

https://discord.com/developers/docs/resources/channel#allowed-mentions-object

I checked the Discord API change log and didn't see a mention of this, and based off of when my webhooks stopped working, I believe they made this change sometime yesterday.

**Comment by lovvskillz** [comment]
I updated the docs 👍
