### ISSUE TITLE
Webhook status code 400: {"embeds": ["0"]}

### ISSUE THREAD

**Issue by Araid0628** [lovvskillz/python-discord-webhook#16]
I tried to send message with embed field to my discord channel through webhook. Types of startSellDate, publicType and skusList are all 'str'. After execute(), it returns code 400 error.

# env
discord-webhook version is 0.6.0.

# code
def discordEmbedMessage(sneakerInfo, startSellDate, publicType, imageURL, skusList):
    # descirption = "test"
    # create embed object for webhook
    embed = DiscordEmbed(title=sneakerInfo, description="发现新款", color=242424)
    embed.add_embed_field(name='Sell Date', value=startSellDate, inline=False)
    embed.add_embed_field(name='Public Type', value=publicType, inline=False)
    embed.add_embed_field(name='SkusList', value=skusList, inline=False)
    # set image
    embed.set_image(url=imageURL)
    # set footer
    embed.set_footer(text='Coldplay')
    # add embed object to webhook
    webhook.add_embed(embed)
    response = webhook.execute()

**Comment by Araid0628** [comment]
One of these parameters is null. Solved.

**Comment by idadean911** [comment]
how did you fix it? i need a solution

**Comment by lovvskillz** [comment]
Please check your parameters. Maybe one of these is also null/None.

**Comment by Dmunch04** [comment]
same thing happens to me, but only when i try and add an image or thumbnail
