### ISSUE TITLE
embed.timestamp = time is off

### ISSUE THREAD

**Issue by victor46** [lovvskillz/python-discord-webhook#19]
Weird issue where when posting to the webhook and displaying the timestamp in the embed the time is off by a few minutes.  Is there somewhere we can have this run more frequently, maybe a for loop?  I've seen it come as far off as 30-60 mins.    I'm not sure I completely understand where you are calling for the time to be updated, but would appreciate any assistance.  Using latest code.

![image](https://user-images.githubusercontent.com/18334224/76451301-9a6fe700-63a5-11ea-833f-1d4340c6f849.png)

In image, the time in the lower left is my system timestamp that is being run on my script at the time of execution, and the time in the embed is the after result from posting to Discord.

**Comment by victor46** [comment]
Now getting some timestamps that are more than 24 hours off.

**Comment by lovvskillz** [comment]
Hi,
you can update the timestamp with `embed.set_timestamp()` in your loop.
Then replace the embed in your webhook with the updated one.
```python
webhook.remove_embed(0) # 0 is the index of the embed
webhook.add_embed(embed)
webhook.execute()
```
Hope this helps you.

**Comment by victor46** [comment]
Hi there - Thanks for this, however where can I find the index of the embed?  It keeps coming back with 'IndexError: pop from empty list'

**Comment by lovvskillz** [comment]
I have now tested it myself and realised that this was a bug.
Please test it with the updated package `0.7.1`

To fix the IndexError, simply remove the embed after you executed the webhook.
```python
webhook.add_embed(embed)
webhook.execute()
webhook.remove_embed(0)
```

**Comment by victor46** [comment]
Thank you so much!  The updated package fixed the issue!
