### ISSUE TITLE
Colour Format

### ISSUE THREAD

**Issue by syntax** [lovvskillz/python-discord-webhook#22]
What is the format for the colour when using the embed libary?

Say I wanted to show the hex colour #ffa800 , how would I represent this in the formatting the libary requires?

**Comment by syntax** [comment]
Solved, am being stupid. Just convert the hex into decimal, for anyone wondering.

https://www.rapidtables.com/convert/number/hex-to-decimal.html

**Comment by Tithen-Firion** [comment]
Just replace `#` with `0x` to tell Python it's a hexadecimal integer. Try it yourself, type `0xffa800` in Python shell.
