### ISSUE TITLE
Webhook rate limiting

### ISSUE THREAD

**Issue by thecanoechief** [lovvskillz/python-discord-webhook#23]
Hi, when my discord webhook gets rate limited, this module prints out the error message which I do not want to happen. Is there any way to stop it from printing out likes this? Also is there any other handling of rate limits that I don't know about? Thank you!!

**Comment by thecanoechief** [comment]
![Capture](https://user-images.githubusercontent.com/29711425/85240884-72117300-b3ff-11ea-9585-94647cbb924d.PNG)

**Comment by lovvskillz** [comment]
you could set the logging level to "critical".
```python
import logging
logging.getLogger("discord_webhook").setLevel(logging.CRITICAL)
```
