### ISSUE TITLE
What errors can occur?

### ISSUE THREAD

**Issue by yuto51942** [lovvskillz/python-discord-webhook#24]
Hello.

I want to implement exception handling, but I don't know what kind of error will occur.
Are there any user defined exceptions?

**Comment by lovvskillz** [comment]
I have not defined any own exceptions for this.
If there is a network problem [requests](https://requests.readthedocs.io/en/master/) should raise an [exception](https://requests.readthedocs.io/en/master/user/quickstart/#errors-and-exceptions).

**Comment by yuto51942** [comment]
@lovvskillz Thank you!
