### ISSUE TITLE
[Feature Request] Support allowed mentions

### ISSUE THREAD

**Issue by arxenix** [lovvskillz/python-discord-webhook#27]
Discord webhooks support an `allowed_mentions` field, which sets the allowed mention types for the message. This is needed in some cases to prevent webhooks from tagging people/roles/`@everyone` when they contain user-controlled data.

https://discord.com/developers/docs/resources/webhook#execute-webhook

https://discord.com/developers/docs/resources/channel#allowed-mentions-object

**Comment by lovvskillz** [comment]
I added this feature into the 0.9.0 release.
You can find an example in the [readme](https://github.com/lovvskillz/python-discord-webhook#allowed-mentions) file.
