### ISSUE TITLE
Adding Hyperlink to Embed Field 

### ISSUE THREAD

**Issue by NinoSoles** [lovvskillz/python-discord-webhook#29]
is there a way to add a Hyperlink to the added fields in an embed? Instead of having the value can I have name of the field be a hyperlink? Something like this where the fields under Sizes have a hyperlink
<img width="531" alt="Screen Shot 2020-09-23 at 11 45 53 PM" src="https://user-images.githubusercontent.com/49324619/94098585-ee4c9580-fdf6-11ea-9044-cf3d6d412961.png">

**Comment by lovvskillz** [comment]
you can use simple markdown
```python
embed.add_embed_field(name='Link', value='[go to google.com](https://www.google.com/)')
```
![image](https://user-images.githubusercontent.com/14542790/94149977-de759580-fe78-11ea-96b6-7a48b2d46773.png)

bold text:
```python
embed.add_embed_field(name='Link', value='**[go to google.com](https://www.google.com/)**')
```
![image](https://user-images.githubusercontent.com/14542790/94150007-e9c8c100-fe78-11ea-984f-be452d46ed0a.png)

**Comment by NinoSoles** [comment]
Is there a character limit for the value field?

**Comment by NinoSoles** [comment]
Character limit appears to be 1400, is there anyway it can be raised?

**Comment by lovvskillz** [comment]
I assume that this limit is set by Discord. I don't think that this can be changed.
