### ISSUE TITLE
[Feature Request] Async Webhook Generation and Messaging

### ISSUE THREAD

**Issue by GenerelSchwerz** [lovvskillz/python-discord-webhook#30]
I'd like to request asynchronized webhook generation, looping, and message sending since I am experiencing performance issues while the webhooks are synchronous.

Error log:
```python
TypeError: object Response can't be used in 'await' expression
Ignoring exception in on_guild_channel_create
Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 333, in _run_event
    await coro(*args, **kwargs)
  File "C:/Users/User/Desktop/Discord Shit/gen-bot/testwebhook.py", line 221, in on_guild_channel_create
    await webhook.execute()
TypeError: object Response can't be used in 'await' expression
Ignoring exception in on_guild_channel_create
Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 333, in _run_event
    await coro(*args, **kwargs)
  File "C:/Users/User/Desktop/Discord Shit/gen-bot/testwebhook.py", line 221, in on_guild_channel_create
    await webhook.execute()
TypeError: object Response can't be used in 'await' expression 
```

**Comment by GenerelSchwerz** [comment]
Following up on this request, just a reminder. Having async operations would greatly improve the versatility of multiple webhooks and can help larger bots be less clogged up/caught up in sync operations.

**Comment by GenerelSchwerz** [comment]
Is this library dead or am I not receiving a response because I asked something inappropriate? I hope that this will be implemented, I will continue to wait.

**Comment by lovvskillz** [comment]
It is not dead. But I don't have much time right now.

**Comment by GenerelSchwerz** [comment]
Good to know, can't wait to hear back from you!

**Comment by GenerelSchwerz** [comment]
Just a follow-up, I think this would be pretty easy to implement if you switched from the requests dependency to httpx.

Link to it: https://github.com/encode/httpx

It has the same functionality as requests but with async support and better resource manangement.
Take what I say with a grain of salt though, I'm not overly familiar with the library  and it is still technically in alpha.

**Comment by sivulich** [comment]
Hi @GenerelSchwerz you can wrap the sending of the messages in a task queue like celery, this would help you improve performance and also is a good practice to separate the API calls (as they have varying response times) from the main execution.

**Comment by ResetXD** [comment]
> Following up on this request, just a reminder. Having async operations would greatly improve the versatility of multiple webhooks and can help larger bots be less clogged up/caught up in sync operations.

why not use aioify module .just use your webhook events in aioify obj
