### ISSUE TITLE
Latest commit broke webhook

### ISSUE THREAD

**Issue by codekuu** [lovvskillz/python-discord-webhook#32]
Hi,
Seems like:
https://github.com/lovvskillz/python-discord-webhook/commit/b6d6eeef1aadca0226a0ca9bc6722ffa892d468f#diff-fac559e83caf3a7ecc24b38e4a1db87022fa73c81a427a1e18f090216b85adbcR139
Broke the latest version of discord_webhook.

When sending messages to multiple webhooks using:

```
message = "Test123\n"
webhook = DiscordWebhook(url=['XXXX', 'XXXXX'], content=message)
webhook.execute()
```

Result:
```
File "/usr/local/lib/python3.8/site-packages/discord_webhook/webhook.py", line 139, in execute
    self.sent_message_id = json.loads((responses[0] if len(responses) == 1 else responses).content.decode('utf-8'))['id']
AttributeError: 'list' object has no attribute 'content'
```

**Comment by codekuu** [comment]
@webtax-gh have a look at it 👍

**Comment by lovvskillz** [comment]
@codekuu I fixed this issue in the latest release. Please use the version 0.11.0

**Comment by codekuu** [comment]
Awesome, looked at the latest commit regarding multiple webhooks, looks great, Thanks!
