### ISSUE TITLE
Error sending multiple webhooks

### ISSUE THREAD

**Issue by NinoSoles** [lovvskillz/python-discord-webhook#34]
I receive this error when sending a webhook to multiple webhook urls

` File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/requests/sessions.py", line 731, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No connection adapters were found for '['https://discordapp.com/api/xxx', 'https://discordapp.com/api/webhooks/xxx']'
`

My code 
`
def send_webhook(link, quantiy, info, webhook):
    webhook_links = ['https://discordapp.com/api/webhooks/xxx, 'https://discordapp.com/api/webhooks/xxx']
    webhook = DiscordWebhook(url=webhook)
    embed = DiscordEmbed(title = info[1] ,color = 242424, url=link, description='${} - Quantiy Available {}'.format(info[2], quantiy))
embed.set_thumbnail(url = info[0])
    webhook.add_embed(embed)
    webhook.execute()
`

**Comment by lovvskillz** [comment]
In order to use multiple URLs, you must use at least version `0.6.0`.
