### ISSUE TITLE
avatar_url dont process the url 

### ISSUE THREAD

**Issue by andresfcardenas** [lovvskillz/python-discord-webhook#36]
Hi guys, currently y have next lines and the avatar_url parameter dont update the webhook image, do you know why happen this?did I forget something before building the webhook?

![image](https://user-images.githubusercontent.com/1001780/101736698-d3063380-3a91-11eb-95f9-4f3fda54cdfd.png)

regards! :D

**Comment by andresfcardenas** [comment]
Update: the webhook show all info successfully in my discord server but the avatar dont update when i use the avatar_url parameter, regards!

**Comment by lovvskillz** [comment]
That's very strange. 
For me, the avatar image can be displayed without any problems. 
Have you already checked if the URL is correct and publicly accessible?

**Comment by andresfcardenas** [comment]
hi! yes, the image is public and the url is correct, the problem begin when i was activate https in my server, i can see de images in the browser but discord dont recognize the image, is very strange. :(

**Comment by andresfcardenas** [comment]
Hi again! the problem has been resolved, in this link discord mentioned this problem and say that several dns providers have problems with image loads https://support.discord.com/hc/en-us/articles/360034366151 they recomend google dns or cloudflare dns, previewsly i used digital ocean but update to cloudflare the problem was resolved!!! regards and merry christmas
