### ISSUE TITLE
ModuleNotFoundError: No module named 'discord_webhook'

### ISSUE THREAD

**Issue by Uhnitials** [lovvskillz/python-discord-webhook#39]
Reinstalled python and I checked environment paths. Tried pip3 install, tried running script as python3, python, and py.

Dont know what to do anymore I also reinstalled the library.

**Comment by r1bnc** [comment]
Try to do it in a virtualenv?
How about other pip packages?

**Comment by nsde** [comment]
I get the same error. I double-checked everything and tried to install it manually...

**Comment by klrmac** [comment]
I'm having the same issue using VSCode. I tried everything and it's still not working.

**Comment by jindalpriyanshu101** [comment]
Just reinstall the module and make sure you using the correct python path where you got this module installed. or you can try `pip install --upgrade discord-webhook`

I experienced the same on VS Code but got it fixed by reinstalling the module.
