### ISSUE TITLE
DiscordEmbeds getting posted multiple times when reusing DiscordWebhook instance.

### ISSUE THREAD

**Issue by vremes** [lovvskillz/python-discord-webhook#45]
Hey,

I took a look at `DiscordWebhook.json` property which is accessed in `DiscordWebhook.execute` method.

When you call `DiscordWebhook.execute()` method in your Python code there are still DiscordEmbeds in `self.embeds` after the call because `self.embeds` never gets emptied in the current code.

Example from the [DiscordWebhook.json](https://github.com/vremes/python-discord-webhook/blob/e6625cf682faaeb147552aecd2607ceb6d5ae81f/discord_webhook/webhook.py#L87) property:

 1. `self.embeds` are stored into `embeds` variable
 2. `self.embeds` is set to empty `list`
 3. `for` loop loops through `embeds` variable and adds them to `self.embeds` using `self.add_embed`

**Outcome**: future calls to `execute()` using same instance will contain duplicate `DiscordEmbed` instances.

Is this design choice or an oversight by the developer?

e.g. is it up to the user of this module to remove embeds using `remove_embed` method after `execute` is called to avoid this situation?

I left a comment to issue https://github.com/lovvskillz/python-discord-webhook/issues/1#issuecomment-787444795

Here is example code which highlights the issue:
```python
import time
from discord_webhook import DiscordWebhook, DiscordEmbed

discord_webhook = DiscordWebhook(url=['https://discord.com/api/webhooks/...........'])

for i in range(1, 10):
    embed = DiscordEmbed(title=i, description='Test {}'.format(i))
    discord_webhook.add_embed(embed)
    discord_webhook.execute()
    time.sleep(1)
```

discord-webhook version: 0.11.0

**Comment by vremes** [comment]
I have made changes to my fork, closes this issue and #40

https://github.com/vremes/python-discord-webhook/commit/c447a4b51b3fe1be1edfe11559019fab448be69f

**Comment by lovvskillz** [comment]
@vremes  Thank you for your contribution. Would be great if you could create a pull request

**Comment by vremes** [comment]
Hey, thanks for getting back to me.

I created a pull request #48
