### ISSUE TITLE
Split message when too much character

### ISSUE THREAD

**Issue by mrsachou** [lovvskillz/python-discord-webhook#50]
Hello, when message contains too much character its cut , is this possible to split the message ?

**Comment by r1bnc** [comment]
Maybe just cut the string before passing it into this program?

**Comment by novasz** [comment]
Or send multiple webhooks

**Comment by vremes** [comment]
These limits are enforced by Discord: https://discord.com/developers/docs/resources/channel#embed-limits

In my opinion you should handle too long messages/strings in your code as others have already pointed out.
