### ISSUE TITLE
Embed from .txt files?

### ISSUE THREAD

**Issue by ajunior7** [lovvskillz/python-discord-webhook#52]
Using a scraper that that writes to output.txt
![image](https://user-images.githubusercontent.com/40948231/112718516-e5ce3800-8ec9-11eb-9d4f-e5aea4d99c28.png)

I want the webhook to send me the values of "name", "price", and "offerid" from output.txt within the embed, for example:
![image](https://user-images.githubusercontent.com/40948231/112718604-8cb2d400-8eca-11eb-9430-b2ca1fc5102b.png)

but looking at the docs, the embeds in the examples seem to pertain to images, and I am not sure if this would work at all.

**Comment by Tithen-Firion** [comment]
First change your scrapper so it outputs a valid JSON. Then load it in your script:
```python
import json
with open('output.txt', 'r') as f:
    data = json.load(f)
```
Skip the `webhook.add_file` and set the title and the values with `data['name']`, `data['price']` and `data['offerid']`.

**Comment by ajunior7** [comment]
Worked like a charm, thanks!
