### ISSUE TITLE
Embed Youtube Videos

### ISSUE THREAD

**Issue by MrThista** [lovvskillz/python-discord-webhook#53]
Is it possible to embed youtube videos?

**Comment by lovvskillz** [comment]
You can only include the video URL in the embed as a description.
```python
webhook = DiscordWebhook(url=url, content='content')
embed = DiscordEmbed(title='Embed Title', description='VIDEO URL')
webhook.add_embed(embed)
response = webhook.execute()
```
However, [no preview image is displayed](https://support.discord.com/hc/en-us/community/posts/360037387352-Videos-in-Rich-Embeds?page=1#comments).
If you want a preview to be displayed, you must submit the webhook without an embed.

**Comment by MrThista** [comment]
That's great, thanks for the reply.
