### ISSUE TITLE
Cannot send an image with a file path

### ISSUE THREAD

**Issue by KhushC-03** [lovvskillz/python-discord-webhook#54]
webhook = DiscordWebhook(url=Webhook_URL, username=whn)
    embed = DiscordEmbed(title=':tada: Footlocker In Store Raffle Confirmed! :tada:', color=65042)
    embed.set_thumbnail(url=icon)
    embed.set_author(name=whn)
    embed.set_footer(text=f'| Alliance IO CLI | {Version} | FTL |', icon_url='https://static.wixstatic.com/media/7e8497_64f1127cd3b54ca1abf4155599062906~mv2.png/v1/fill/w_40,h_40,al_c,q_85,usm_0.66_1.00_0.01/Profile%20Picture.webp')
    embed.set_timestamp()
    embed.add_embed_field(name='Email 📧:', value="||"+email+"||",inline=False)
    embed.add_embed_field(name='Size :', value=size)
    embed.add_embed_field(name='Reservation ID:', value="||"+reservationid+"||",inline=False)
    embed.add_embed_field(name='Shoe-ID 🏷:', value=sku,inline=False)
    embed.add_embed_field(name='Winning Store :', value=store1,inline=False)
    embed.add_embed_field(name='Task Number:', value=TA,inline=False)
    embed.set_image(url='path to file')
    webhook.add_embed(embed) 
    try:                       
        response = webhook.execute()   
    except Exception as ex:
        print('Webhook Failure, Raffle Has Been Entered!')

When trying to send a local picture (png) im returned with the status code 400.

**Comment by aarav2you** [comment]
You havent defined `embed.set_image(url='path to file')`

**Comment by KhushC-03** [comment]
> You havent defined `embed.set_image(url='path to file')`

If I change it to an image url it works.

**Comment by sivulich** [comment]
Hi @KhushC-03 as the readme suggest, you must upload as a file and then link it:
```python
from discord_webhook import DiscordWebhook, DiscordEmbed

webhook = DiscordWebhook(url='your webhook url')

with open("path/to/image.jpg", "rb") as f:
    webhook.add_file(file=f.read(), filename='example.jpg')

embed = DiscordEmbed(title='Embed Title', description='Your Embed Description', color='03b2f8')
embed.set_thumbnail(url='attachment://example.jpg')

webhook.add_embed(embed)
response = webhook.execute()
```
