### ISSUE TITLE
Adding embeds in DiscordWebhook initializator throws an error when executing

### ISSUE THREAD

**Issue by espoem** [lovvskillz/python-discord-webhook#7]
While trying to pass a list of embeds to DiscordWebhook constructor, the execute method throws `TypeError: Object of type 'DiscordEmbed' is not JSON serializable`.

Simple testing code:

```python
from discord_webhook import DiscordWebhook, DiscordEmbed

if __name__ == "__main__":
    embed = DiscordEmbed(title="Test embed")
    webhook = DiscordWebhook(url="Valid Webhook URL", embeds=[embed])
    webhook.execute()
```

**Comment by lovvskillz** [comment]
Thanks for reporting this issue. I fixed that in version `0.4.1`
