### ISSUE TITLE
Changing the style of the fields

### ISSUE THREAD

**Issue by marcofucito** [lovvskillz/python-discord-webhook#70]
Hi,
Is it possible to change the style of the fields?
I would like to reverse the style of the Fields:
Put the name of the fields in gray, and the value in bold

like in the following screen

<img width="436" alt="image" src="https://user-images.githubusercontent.com/23509784/137760356-ff8691e7-50a2-48b9-a8f4-61d9e10f8597.png">

Thank you

**Comment by lovvskillz** [comment]
just swap the values
```python
embed.add_embed_field(name='YOUR VALUE', value='YOUR NAME')
embed.add_embed_field(name='YOUR NEXT VALUE', value='YOUR NEXT NAME')
```
