### ISSUE TITLE
No Reading last line from attached file 

### ISSUE THREAD

**Issue by yousafriaz** [lovvskillz/python-discord-webhook#72]
I am trying to atached a text file 
                            with open("datasets/uploads/discord.txt", "rb") as f:
                                webhook.add_file(file=f.read(), filename='discord.txt')
But every time it does not print last lines in the file

**Comment by Vault108** [comment]
Would you mind pasting your entire code any error messages you are getting? 
Are you trying to print the entire file? or just the last line?
