### ISSUE TITLE
Can't remove files when using webhook.edit()

### ISSUE THREAD

**Issue by breadcat-rr** [lovvskillz/python-discord-webhook#73]
Files don't get removed by `webhook.remove_files()` when using `webhook.edit()`

```
from discord_webhook import DiscordWebhook
from time import sleep
from PIL import Image
from io import BytesIO

webhook = DiscordWebhook(url, content='Image test')
sent_webhook = webhook.execute()

img = Image.new('RGB',(64,64),'#f00')

while True:
	io = BytesIO()
	img.save(io,'JPEG')
	io.seek(0)

	webhook.add_file(file=io,filename='test.jpeg')
	webhook.edit(sent_webhook)
	webhook.remove_files()

	sleep(2)
```

**Comment by vremes** [comment]
Hey @breadcat-rr,

This still seems to be an issue, right?

Tell me if i'm mistaken:
1. Webhook sends a message to discord, no files attached
2. Code creates an image and enters infinite `while` loop
3. Code creates a new webhook instance with a file attached to it
4. Code overwrites the new webhook instance using `edit()` method and sends the request
5. The expected output is `Image test` but instead the webhook still sends the attached file

**Comment by lovvskillz** [comment]
In version 0.15.0 you can pass an attachments list as a parameter to the edit function. With this you can edit existing attachments or pass an empty list to delete all files.

```python
webhook.remove_files()
webhook.edit(sent_webhook, attachments=[])
```

**Comment by RandomModderJDK** [comment]
I think this issue should be reopened as it exists since version 1.0.0 again
