### ISSUE TITLE
Webhooks don't execute

### ISSUE THREAD

**Issue by MinerChAI** [lovvskillz/python-discord-webhook#8]
status code 400: <?xml version='1.0' encoding='UTF-8'?><Error><Code>InvalidArgument</Code><Message>Invalid argument.</Message><Details>POST object expects Content-Type multipart/form-data</Details></Error>

**Comment by lovvskillz** [comment]
could you provide more details like your code?

**Comment by MinerChAI** [comment]
```py
wh = DiscordWebhook(url='https://cdn.discordapp.com/api/webhooks/548562668223725569/MYPKHBCbVorW4L_4Z1hd63J5BFhOCMbdYTdGkTcasvxSzVWdmORqaFI_nRSLTe6UQTZA', content='Test')
```

**Comment by MinerChAI** [comment]
LOL it's just an error in webhook URL
