### ISSUE TITLE
Question: Does this require a specfic API version?

### ISSUE THREAD

**Issue by SnowyJaguar1034** [lovvskillz/python-discord-webhook#81]
With the termination of discord's V6 and V7 API's I'm just wondering if this library makes use of any specific API version? as I don't want to start making use of a library that then gets discontinued.

Also on another topic can I use properties/attributes (I don't know the proper word) from discord.py's lib with this one, such as their colors for embeds or even their embed object as a whole? I'm currently using bog-standard messages for my bot's shard events and I'm thinking of moving over to using this lib's webhooks instead. I have embeds like this one `embed = discord.Embed(title=f"Shard {shard} Ready", colour=discord.Colour.green(), timestamp=datetime.datetime.utcnow(),)` and I'm wondering if I can just pass discord.py's embed into the webhook or if not can i at least pass discord.py's colours into discord-webhooks embeds.

Hope that all made sense

The below is what I'm trying to do

```
from discord_webhook import DiscordWebhook
from discord import Embed

webhook = DiscordWebhook(url='your webhook url')

# embed = DiscordEmbed(title='Your Title', description='Lorem ipsum dolor sit', color='03b2f8')
embed = Embed(title=f"Shard {shard} Ready", colour=discord.Colour.green(), timestamp=datetime.datetime.utcnow(),)

webhook.add_embed(embed)

response = webhook.execute()
```
or something like this
```
from discord_webhook import DiscordWebhook, DiscordEmbed
from discord import Colour

webhook = DiscordWebhook(url='your webhook url')

embed = DiscordEmbed(title='f"Shard {shard} Ready", color=Colour.green(), timestamp=datetime.datetime.utcnow())

webhook.add_embed(embed)

response = webhook.execute()
```

**Comment by vremes** [comment]
Hey,

>With the termination of discord's V6 and V7 API's I'm just wondering if this library makes use of any specific API version? as I don't want to start making use of a library that then gets discontinued.

This library does not depend on any versioned Discord API endpoints, it consumes only webhook URLs which are not versioned, for example `https://discord.com/api/webhooks/xxxxxxxxxxxxxx/yyyyyyyy`

>Also on another topic can I use properties/attributes (I don't know the proper word) from discord.py's lib with this one, such as their colors for embeds or even their embed object as a whole?

I took a look at discord.py docs and according to their documentation `discord.Colour.green()` should return an instance of `discord.Colour` with a value of `0x2ecc71`.

[Documentation here](https://discordpy.readthedocs.io/en/stable/api.html#discord.Colour.green)

As as result, you **can** use `discord.Colour` with this library, here is example code:
```py
from discord import Colour
from discord_webhook import DiscordWebhook, DiscordEmbed

webhook = DiscordWebhook(url='webhook url here')

embed = DiscordEmbed(title="Test")
embed.set_timestamp()

# Pick random color and pass the value to set_color
color = Colour.random().value
embed.set_color(color)

webhook.add_embed(embed)
response = webhook.execute()
```

As you can see, we pass the `value` property value to `set_color` method and it works!

> I'm wondering if I can just pass discord.py's embed into the webhook 

Unfortunately this is not possible currently.

I hope this helps!

**Comment by SnowyJaguar1034** [comment]
Hi thanks for getting back to me, all of those answers make sense and I'll be making use of them.
