### ISSUE TITLE
ImportError: cannot import name 'asynccontextmanager'

### ISSUE THREAD

**Issue by Frag1337** [lovvskillz/python-discord-webhook#87]
```python
  File "..\addons\source-python\plugins\SurfTricks\libs\misc\discord.py", line 30, in <module>
    from discord_webhook import DiscordEmbed
  File "..\addons\source-python\packages\custom\discord_webhook\__init__.py", line 5, in <module>
    from .async_webhook import AsyncDiscordWebhook
  File "..\addons\source-python\packages\custom\discord_webhook\async_webhook.py", line 4, in <module>
    from contextlib import asynccontextmanager

ImportError: cannot import name 'asynccontextmanager'
```

Python 3.6.1

**Comment by GhostOps77** [comment]
[contextlib](https://github.com/python/cpython/blob/3.10/Lib/contextlib.py) is an in-built module that comes with cpython. It must be available to everyone by default. The Async Webhook class works fine for me. Try installing that module again in ur system

**Comment by Frag1337** [comment]
In Python 3.6.1 theres no asynccontextmanager, and I cannot upgrade or downgrade from there.

asynccontextmanager has been added to 3.7

https://docs.python.org/3/whatsnew/3.7.html#contextlib

**Comment by GhostOps77** [comment]
I don't know whether my commit works or not, but just try it by pip installing that module

**Comment by Frag1337** [comment]
It works fine on load after installing contextlib2. Thanks
