### ISSUE TITLE
Does rate_limit_retry keep the server running?

### ISSUE THREAD

**Issue by eliezerp3** [lovvskillz/python-discord-webhook#89]
Hi. Thank you for this package. Does rate_limit_retry keep the server alive until it is able to make the requests? Meaning will i be charged for the wait when running on a serverless hosting service that charges per the seconds your container is running?

**Comment by lovvskillz** [comment]
The package tries to send the webhook in a loop if it is being rate limited. So you would be charged until the webhook is sent.

**Comment by eliezerp3** [comment]
Appreciate the response
