### ISSUE TITLE
Webhook won't execute, TypeError: Object of type Asset is not JSON serializable

### ISSUE THREAD

**Issue by DutchDavyy** [lovvskillz/python-discord-webhook#9]
Whenever I try to have the webhook execute I get the following error, and I can't seem to be able what causes it.

[https://pastebin.com/QrZZpBHC](url)

My code:

[https://pastebin.com/b4dCmapr](url)

Help would be appreciated :)

**Comment by lovvskillz** [comment]
Could you debug your code and check if you included any data that is not serializable?

**Comment by DutchDavyy** [comment]
> Could you debug your code and check if you included any data that is not serializable?

Certainly, I however have no clue what is and what is not serializable, so I have printed the output of all the tweet.Something inside the code, aswell as user avatar urls I am calling in that part of the code, I hope you can spot the error so I can get it to work ^.^

![tweet something](https://user-images.githubusercontent.com/24512017/58803390-ab6a1b80-860f-11e9-8e73-5c087bc23d95.PNG)

I'll also paste them as text here:

`
Tweet detected, content: Test | tweeted at: 2019-06-03 12:51:35
tweet.text = Test
tweet.created_at = 2019-06-03 12:51:35
tweet.in_reply_to_screen_name = None
tweet.retweet_count = 0
tweet.favorite_count = 0
tweet.reply_count = 0
tweet.user.url = None
cane.avatar_url = https://cdn.discordapp.com/avatars/465529983301844992/3813188b483e90888e27e7d43ab7c44f.webp?size=1024
bot.user.avatar_url = https://cdn.discordapp.com/avatars/581057501332766750/6e9502ced4f72938a11a359f0d3dfa87.webp?size=1024
`
aswell as the pastebin with the text, hope that will be sufficient!

[https://pastebin.com/zzH0du5E](url)

**Comment by lovvskillz** [comment]
Can you also post the content of `webhook.json`?
