### ISSUE TITLE
NameError: name 'DiscordEmbed' is not defined

### ISSUE THREAD

**Issue by CColdFox** [lovvskillz/python-discord-webhook#92]
line: `embed = DiscordEmbed(title=(embedtitle), description=(embeddesc), color=(embedcolor))`

**Comment by vremes** [comment]
Hey, could you share your imports?

Make sure you import `DiscordEmbed` from `discord_webhook`:
```py
from discord_webhook import DiscordEmbed

embed = DiscordEmbed(title=(embedtitle), description=(embeddesc), color=(embedcolor))
```

**Comment by CColdFox** [comment]
Hi! Here's my imports:
```python
import json
import requests
import discord_webhook
import time
from pystyle import *
```
I'll try only importing "DiscordEmbed".

**Comment by CColdFox** [comment]
So I tried "from discord_webhook import DiscordEmbed" and it says that "webhook" is not defined (from the "webhook.execute()" line). So I tried this:
```python
from discord_webhook import webhook, DiscordEmbed
```
And now it says:
```python
File "C:\Users\CColdFox\Desktop\My Projects\Python\Novus\main.py", line 145, in main
    webhook.add_embed(embed)
AttributeError: module 'discord_webhook.webhook' has no attribute 'add_embed'
```

**Comment by vremes** [comment]
Yeah, you have to import `DiscordWebhook` and `DiscordEmbed` from `discord_webhook`.

The you create instances of `DiscordWebhook` and `DiscordEmbed`.

Your code should look something like this:
```py
from discord_webhook import DiscordWebhook, DiscordEmbed

webhook = DiscordWebhook(url='webhook-url-here')

embed = DiscordEmbed(title='My title', description='My description', color='03b2f8')

webhook.add_embed(embed)

response = webhook.execute()
```
