### ISSUE TITLE
DiscordEmbed is broken as of 0.16.2

### ISSUE THREAD

**Issue by rcdailey** [lovvskillz/python-discord-webhook#99]
See the error [here](https://github.com/rcdailey/recyclarr/runs/6431431242?check_suite_focus=true#step:5:336) and my script [here](https://github.com/rcdailey/recyclarr/blob/master/ci/notify/discord_notify.py).

> discord_webhook.webhook_exceptions.ColourNotInRangeException: 'None is not in valid range of colors. The valid ranges of colors are 0 to 16777215 inclusive (INTEGERS) and 0 to FFFFFF inclusive (HEXADECIMAL)'

**Comment by lovvskillz** [comment]
You could set a color for your embed.

**Comment by lovvskillz** [comment]
fixed in 0.16.3 #

**Comment by rcdailey** [comment]
The point is that this is a backwards breaking change. I think the way I have it should still work. This seems like a bug to me. Unfortunately, with the way I run my notify pipeline, I cannot rerun it with changes on my side. However if you fix this I can rerun it. 

I hope that you consider a fix. Thank you.
